package homework.tests;// Generated by Selenium IDE

import homework.testbase.TestBase;
import org.junit.Test;

public class AutoTestsOneTest extends TestBase {


    @Test
    public void userLogin() throws InterruptedException {
        navigationHelper.openLoginPage();
        navigationHelper.setPageSize();
        loginHelper.inputMailAndPasswordAndLogin(new AccountData("daniils1406@mail.ru", "Landrover2013"));
        navigationHelper.openMainPage();
        logoutHelper.logout();
    }
}
