package homework.tests;// Generated by Selenium IDE

import homework.generator.Generator;
import homework.generator.model.HabiticaTask;
import homework.generator.model.jaxb.Tasks;
import homework.testbase.TestBase;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameter;
import org.junit.runners.Parameterized.Parameters;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import java.io.File;
import java.util.List;

import static java.lang.Thread.sleep;

@RunWith(Parameterized.class)
public class CreateTaskTest extends TestBase {

    @Parameter
    public HabiticaTask tasks;

    @Parameters(name = "tasks")
    public static List<HabiticaTask> taskCreationTestCase() {
        try {
            JAXBContext context = JAXBContext.newInstance(Tasks.class);
            Unmarshaller unmarshaller = context.createUnmarshaller();
            Tasks posts = (Tasks) unmarshaller.unmarshal(new File(Generator.SOURCE + "/tasks.xml"));
            return posts.getTasks();
        } catch (JAXBException exception) {
            throw new RuntimeException(exception);
        }
    }


    @Test
    public void createTask() throws InterruptedException {
        navigationHelper.openLoginPage();
        navigationHelper.setPageSize();
        loginHelper.inputMailAndPasswordAndLogin(new AccountData("daniils1406@mail.ru", "Landrover2013"));
        navigationHelper.openMainPage();
        sleep(5000);
        createSiteTask(tasks.getName());
        logoutHelper.logout();
    }

    private void createSiteTask(String taskName) {
        driver.manage().window().setSize(new Dimension(945, 1020));
        driver.findElement(By.cssSelector(".ml-75")).click();
        driver.findElement(By.cssSelector(".dropdown-item:nth-child(1) > .task-label")).click();
        driver.findElement(By.cssSelector(".input-title")).click();
        driver.findElement(By.cssSelector(".input-title")).sendKeys(taskName);
        driver.findElement(By.cssSelector(".btn-footer")).click();
    }
}
