package homework.tests;// Generated by Selenium IDE

import homework.testbase.TestBase;
import org.junit.Test;

import static java.lang.Thread.sleep;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

public class CreateTask extends TestBase {
    @Test
    public void homework2() {
        navigationHelper.openLoginPage();
        navigationHelper.setPageSize();
        loginHelper.inputMailAndPasswordAndLogin(new AccountData("daniils1406@mail.ru", "Landrover2013"));
        navigationHelper.openMainPage();
        createSiteTask();
    }

    private void createSiteTask(){
        driver.manage().window().setSize(new Dimension(945, 1020));
        driver.findElement(By.cssSelector(".ml-75")).click();
        driver.findElement(By.cssSelector(".dropdown-item:nth-child(1) > .task-label")).click();
        driver.findElement(By.cssSelector(".input-title")).click();
        driver.findElement(By.cssSelector(".input-title")).sendKeys("testname");
        driver.findElement(By.cssSelector(".btn-footer")).click();
    }
}
