package homework.tests;// Generated by Selenium IDE

import homework.generator.Generator;
import homework.generator.model.HabiticaUser;
import homework.generator.model.jaxb.Users;
import homework.testbase.TestBase;
import org.junit.Test;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import java.io.File;

import static java.lang.Thread.sleep;

public class LoginTest extends TestBase {

    private final Users users;

    public LoginTest() {
        super();
        try {
            JAXBContext context = JAXBContext.newInstance(Users.class);
            Unmarshaller unmarshaller = context.createUnmarshaller();
            users = (Users) unmarshaller.unmarshal(new File(Generator.SOURCE + "/users.xml"));

        } catch (JAXBException exception) {
            throw new RuntimeException(exception);
        }
    }

    @Test
    public void loginWithValidData() throws InterruptedException {
        navigationHelper.openLoginPage();
        navigationHelper.setPageSize();
        loginHelper.inputMailAndPasswordAndLogin(new HabiticaUser(users.getUsers().get(0).getUserName(), users.getUsers().get(0).getPassword()));
//        navigationHelper.openMainPage();
        sleep(1000);
        logoutHelper.logout();
    }

    @Test
    public void loginWithInvalidData() throws InterruptedException {
        navigationHelper.openLoginPage();
        navigationHelper.setPageSize();
        loginHelper.inputMailAndPasswordAndLogin(new HabiticaUser(users.getUsers().get(1).getUserName(), users.getUsers().get(1).getPassword()));
        sleep(1000);
        System.out.println(driver.getCurrentUrl());
    }
}
