// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static java.lang.Thread.sleep;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.interactions.Actions;

import java.util.*;

public class CreateTask extends TestBase {
    @Test
    public void homework2() {
        openHomePage();
        setPageSize();
        inputMailAndPasswordAndLogin(new AccountData("daniils1406@mail.ru", "Landrover2013"));
        openMainPage();
        driver.manage().window().setSize(new Dimension(945, 1020));
        driver.findElement(By.cssSelector(".ml-75")).click();
        driver.findElement(By.cssSelector(".dropdown-item:nth-child(1) > .task-label")).click();
        driver.findElement(By.cssSelector(".input-title")).click();
        driver.findElement(By.cssSelector(".input-title")).sendKeys("testname");
        driver.findElement(By.cssSelector(".btn-footer")).click();
    }
}
